version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
  php:
    build: .
    links:
      - mysql
    volumes:
      - .:/var/www
  mysql:
    image: mysql:5.7
    ports:
      - "3333:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: larashop
      MYSQL_USER: user
      MYSQL_PASSWORD: password